export const SET_GAME_STARTED = "SET_GAME_STARTED";
export const SET_DESCRIPTION_EXPANDED = "SET_DESCRIPTION_EXPANDED";
export const SET_GUESS = "SET_GUESS";
export const DECK = {
   FETCH_SUCCESS: "DECK_FETCH_SUCCESS",
   FETCH_ERROR: "DECK_FETCH_EROR",
};
export const CARD_DRAW = {
   FETCH_SUCCESS: "CARD_DRAW_FETCH_SUCCESS",
   FETCH_ERROR: "CARD_DRAW_FETCH_EROR",
};
